OPTIONS_WORDS = {'attractive', 'sometimes', 'some or a little of the time', 'true', 'some times', 'not at all', 'none',
                  'somewhat true', 'not likely', 'often', 'cinco vezes', 'very likely', 'igual',
                  'algumas vezes verdadeira', 'very easy', 'tanto quanto sabe', 'totally',
                  'occasionally or a moderate amount of time', 'um pouco', 'extremamente', 'neither agree nor disagree',
                  'unattractive', 'always', 'a lot', 'some of the time', 'mais ou menos verdadeiro', 'sim',
                  'unappealing', 'raramente', 'concordo totalmente', 'totalmente de acordo', 'provavelmente não', 'não',
                  '1-5 meses', 'fair', 'sempre', 'uma vez', 'às vezes', 'rarely', 'extremely difficult',
                  'discordo totalmente', 'dificuldades graves', 'probably not', 'abaixo da média exigida pela escola',
                  'neither likely nor unlikely', 'yes', 'nada', "i don't like it at all", 'limited a little', 'melhor',
                  'não concordo nem discordo', 'mais que muito', 'probably', 'mais ou menos', 'strongly agree',
                  'frequentemente', 'totally agree', 'insuficiente', 'mais de 1 ano', 'não gosto nada', 'very',
                  'likely', 'not likely at all', 'concordo parcialmente', 'all of the time', 'extremely',
                  'very important', 'strongly disagree', 'disagree slightly', 'none of these', 'uma pouco',
                  'menos de 1 mês', 'duas vezes', 'more than half the days', 'disagree', 'excellent',
                  'none of the time', 'not limited at all', 'uma pouco verdadeira', 'pior', 'poor', 'não sei',
                  'agree strongly', 'falso', 'rarely or none of the time', 'muito', 'nunca', 'limited a lot',
                  'somewhat appealing', 'verdade', 'certainly true', 'daily', 'not difficult at all', 'appealing',
                  'somewhat disagree', 'quatro vezes', 'verdadeiro', 'disagree strongly', 'agree', 'several days',
                  'não sabe', 'most of the time', '6-12 meses', 'discordo parcialmente', 'provavelmente',
                  'a moderate amount of time', 'neither agree or disagree', 'about the same',
                  'muitas vezes ou quase sempre', 'neutral', 'não sabe/não se aplica', 'difficult', 'never',
                  'most or all of the time', 'a little', 'agree slightly', 'very appealing',
                  'neither easy nor difficult', 'very good', 'não é verdadeito', 'pequenas dificuldades',
                  'very difficult', 'mais de cinco vezes', 'dificuldades bem definidas', 'algumas vezes', 'definitely',
                  'três vezes', 'nearly every day', 'good', 'no', 'not true', 'nunca ou raramente',
                  'muito verdadeira ou frequentemente verdadeira', 'não é verdade', 'claro que compraria',
                  'somewhat agree', 'easy'}