AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Java wrapper for Tika for Harmony
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: harmony.HandlerPDF
      Runtime: java11
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      FunctionName: harmony-pdf-parser2